upload task
hombit/sai-tasks2019 pull request #19
Opened 2019-11-19 19:57 UTC by SergeyZHR

Я переосмыслил ТЗ, и переделал

2019-11-23 05:39 UTC, hombit requested changes
Хорошо сделано, но прошу причесать код и изменить формат сохраненных данных. Несколько общих замечаний:
1) Разнесите все по функциям, сделайте main()
2) В этой задаче данных мало, было бы удобнее сохранять их в текстовом формате. Я бы рекомендовал json или просто текстовую таблицу. Кроме того, можно было бы дописывать один большой файл, а не делать много маленьких, но это на ваше усмотрение.
3) В качестве следующего, необязательно, шага, можно было бы попробовать сохранять все в какую-нибудь базу данных.

2019-11-23 05:39 UTC, hombit commented on weather_parse.py
> +#weather underground закрыл api год назад. Да и ну их, с proprietary forecasting system BestForecast(tm)
Перенесите в докстринг, или, еще лучше, в README.md

2019-11-23 05:39 UTC, hombit commented on weather_parse.py
> +lon='42.6675'
Перенесите в main() и вызывайте функции с аргументами

2019-11-23 05:39 UTC, hombit commented on weather_parse.py
> +		sock.connect(('37.29.115.163', 16303))			#сокет сервер метеостанции КГО
«Магические константы» лучше положить в глобальные переменные

2019-11-23 05:39 UTC, hombit commented on weather_parse.py
> +					kgo_vailasa[tmp[0]]=None
Стоит отделить парсинг данных от их получения, сделайте отдельную функцию

2019-11-23 05:39 UTC, hombit commented on weather_parse.py
> +	except Exception as e:
Разве ошибка доступа к сокету — это не то, что должно привести к завершению программы? Кроме того, тут ловятся все исключения, нужно указать конкретный тип

2019-11-23 05:39 UTC, hombit commented on weather_parse.py
> +			except:
Непонятно что именно за исключение тут ловиться? Ошибка перевода во float? Тогда стоит явно указать ValueError

2019-11-23 05:39 UTC, hombit commented on weather_parse.py
> +url='https://api.darksky.net/forecast/'+api_key+'/'+lat+','+lon				#api ссылка
Используйте urllib.parse.urljoin

2019-11-23 05:39 UTC, hombit commented on weather_parse.py
> +except Exception as e:
Разве ошибка получения данных — это не то, что должно привести к завершению программы? Тут не нужно обработать код http, что возвращает сервер вместе с кодом в случае ошибки в запросе? Возможно стоит обработать разные ошибки по-разному, например при timeout можно попробовать спросить сервер еще раз

2019-11-23 05:39 UTC, hombit commented on weather_parse.py
> +with open(path+now.strftime('%Y_%m_%dT%H_%M_%S')+'.pkl',"wb") as f:			#пишем в файл для дальнейшей обработки
Используйте os.path.join для объединения путей, тогда вам не нужно руками ставить разделитель и все будет работать на винде

2019-11-23 05:39 UTC, hombit commented on weather_parse.py
> +# print(datetime.fromtimestamp(mydict['forecast']['data'][-1]['time']) )
Заменить на модульный/интеграционный тест? Стереть?

2019-11-23 19:28 UTC, SergeyZHR commented
Я залил исправленную версию, надо куда-то дальше нажимать? :)

2019-11-24 13:13 UTC, hombit requested changes
Очень хорошо, спасибо за исправления!

Уточню, имел в виду, что описание проекта лучше положить в README.md в вашей папке, как и весь ваш код

2019-11-24 13:13 UTC, hombit commented on weather_parse.py
> +	url=urljoin(urljoin('https://api.darksky.net/forecast/',api_key+'/'),lat+','+lon)			#api ссылка
Переменные lat и lon до сих пор глобальные!

2019-11-24 13:13 UTC, hombit commented on weather_parse.py
> +def main(city,lat,lon):
Имелось в виду, что лучше сделать эти аргументы аргументами функции Darksy_Data

2019-11-26 08:29 UTC, hombit commented
Очень хорошо! Я попробую проверить как работает в ближайшее время. Верните мой ридми, пожалуйста

2019-12-13 11:28 UTC, merged