Моё задание
hombit/sai-tasks2019 pull request #23
Opened 2020-01-11 11:30 UTC by Andrey890

2020-01-11 11:45 UTC, hombit requested changes
Выглядит клево!

Не очень понятна идея программы, имелось в виду, что пользователь указывает конкретную дату, а не просто месяц и год произвольного года. Наверное, можно и так оставить, но может добавить хотя бы дату, когда сделано марсианское фото?

2020-01-11 11:45 UTC, hombit commented on Tavleev/site.py
> +    NASA_API_key = 'API'  # Your NASA_API_key here
Нужен способ подать ключ в программу без изменения её кода. Например, через переменную окружения

2020-01-11 11:45 UTC, hombit commented on Tavleev/site.py
> +def Wiki_text(data):
Лучше использовать готовую библиотеку, типа wikipedia

2020-01-11 11:45 UTC, hombit commented on Tavleev/site.py
> +    return [text, data_final]
Более идиоматично просто `return text, data_final`

2020-01-11 11:45 UTC, hombit commented on Tavleev/site.py
> +        dat = random.randint(2012, 2019)
Что здесь происходит? Почему нельзя просто перебрать годы, пусть и в случайном порядке?

2020-01-11 11:50 UTC, hombit commented on Tavleev/site.py
> +        p = requests.get('https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos', params=par).json()['photos']
Тут выбрасывается `JSONDecodeError`, которое никем не ловится. Вероятно нужно проверить код возврата, там наверняка какой-нибудь 404

2020-01-11 12:31 UTC, Andrey890 commented on Tavleev/site.py
> +        dat = random.randint(2012, 2019)
В некоторые дни фоток нет, в цикле обрабатывается случай их отсутствия (пустой список фоток, len(p)==0)

2020-01-11 12:35 UTC, Andrey890 commented on Tavleev/site.py
> +def Wiki_text(data):
Она возвращает wikitext, который мне не удалось вогнать в сайт. А api вики может вернуть html.

2020-01-11 12:54 UTC, hombit commented on Tavleev/site.py
> +        dat = random.randint(2012, 2019)
Зачем для этого while True и случайный год каждый раз?

2020-01-11 13:09 UTC, hombit commented on Tavleev/site.py
> +def Wiki_text(data):
Ок

2020-01-11 13:09 UTC, hombit commented on Tavleev/site.py
> +    text = requests.get('https://en.wikipedia.org/w/api.php', params=par).json()['parse']['text']['*']
Стоит хотя бы проверить код возврата

2020-01-11 14:05 UTC, Andrey890 commented
Всё переделал, api ключ вводится отдельно вне программы, дата тоже вводится полная.

2020-01-11 16:58 UTC, hombit commented on Tavleev/site.py
> +@app.route('/<data>')
Падает с исключением KeyError, на адресах, которые не поддерживаются. Например, современные браузеры запрашивают всегда http://example.com/favicon.ico, когда приходят на какой-нибудь сайт

2020-01-11 20:50 UTC, Andrey890 commented on Tavleev/site.py
> +@app.route('/<data>')
Поправил, теперь ошибки нет.

2020-01-12 07:42 UTC, hombit commented on Tavleev/site.py
> +@app.route('/<data>')
Причем тут favicon? Потом придет гугл с яндексом и спросят robots.txt, потом снифферы спросят admin.php, а потом пользователь введет не тот урл. Программа не должна падать, если запрашивается несуществующий ресурс, а должна возвращать ответ с кодом 404

2020-01-12 09:45 UTC, Andrey890 commented on Tavleev/site.py
> +@app.route('/<data>')
Поправил, теперь при вводе некорректного URL выдаётся спец. страничка.

2020-01-12 09:50 UTC, merged