Задание Пики сверхновых #13
hombit/sai-tasks2019 pull request #24
Opened 2020-01-11 15:19 UTC by FedotievaAA

2020-01-11 18:06 UTC, hombit requested changes
В целом здорово!

2020-01-11 18:06 UTC, hombit commented on Fedotieva/supernova_peak.py
> +#Find available bands
Но вы же уже нашли все фильтры в массиве band, просто сделайте set(band), чтобы выбрать только уникальные имена

2020-01-11 18:06 UTC, hombit commented on Fedotieva/supernova_peak.py
> +	print(b+' value max\t', mag_[i_max])
Используйте синтаксис форматирования строк для всего, что чуть сложнее сложения двух строк

2020-01-11 18:06 UTC, hombit commented on Fedotieva/supernova_peak.py
> +	raise SystemExit
Стоит пробросить дальше исходное исключение или бросить какое-нибудь более подходящее исключение с сообщением, написанным в принте

2020-01-11 18:06 UTC, hombit commented on Fedotieva/README.txt
> +Замечание: Программа ищет максимум среди имеющихся точек кривой блеска, поэтому если в данном фильтре сверхновая наблюдалась после пикового значения звездной величины, то получаемое значение не будет
Обратите внимание, что иногда в данных есть указание на максимум в какой-нибудь полосе, выводите его тоже. См, например https://sne.space/sne/SN2011fe/

2020-01-11 20:59 UTC, FedotievaAA commented on Fedotieva/supernova_peak.py
> +#Find available bands
Сделала через set(band)

2020-01-11 21:00 UTC, FedotievaAA commented on Fedotieva/supernova_peak.py
> +	print(b+' value max\t', mag_[i_max])
Переделала с использованием f-строк

2020-01-11 21:01 UTC, FedotievaAA commented on Fedotieva/supernova_peak.py
> +	raise SystemExit
Вывожу теперь сообщение возникшего исключения

2020-01-11 21:03 UTC, FedotievaAA commented on Fedotieva/README.txt
> +Замечание: Программа ищет максимум среди имеющихся точек кривой блеска, поэтому если в данном фильтре сверхновая наблюдалась после пикового значения звездной величины, то получаемое значение не будет
Добавила эти данные в начало вывода. Значения совпадают с полученными мной. Возможно, их определяли тем же способом.

2020-01-12 05:55 UTC, hombit requested changes
Все хорошо, но исправьте пожалуйста работу с исключением

2020-01-12 05:55 UTC, hombit commented on Fedotieva/supernova_peak.py
> +except Exception as e:
Лучше сделать так:
```python
except HTTPError as e:
    print(f'Supernova {SN_name} is not found')
    raise e
```
Или
```python
except HTTPError as e:
    print(e)
    raise RuntimeError(f'Supernova {SN_name} is not found')
```
Идея в том, что сообщения об ошибках должны быть выделены. Если исключение не поймано, то сообщение выводится в stderr, а не в stdout, как в случае с принтом

2020-01-12 10:09 UTC, FedotievaAA commented on Fedotieva/supernova_peak.py
> +except Exception as e:
Исправила эту часть

2020-01-12 10:14 UTC, merged