#9 APOD по-русски
hombit/sai-tasks2019 pull request #27
Opened 2020-01-11 22:16 UTC by KOCMOHABT1

2020-01-12 08:08 UTC, hombit requested changes
Вы выполнили не совсем ту задачу. Вам нужно сделать API, который будет работать как NASA APOD API, но добавлять в json поля с информацией на русском

2020-01-12 08:08 UTC, hombit commented on Drozdov/README.md
> +re,
Стандартная библиотека, можно не указывать

2020-01-12 08:08 UTC, hombit commented on Drozdov/README.md
> +
Идея веб-сервиса в том, что пользователь может запросить любой день через http, он не должен иметь доступ к настройкам вашего приложения

2020-01-12 08:08 UTC, hombit commented on Drozdov/apodrus.py
> +
Это все нужно сделать один раз при старте программы или, хотя бы, вынести в отдельную функцию.

2020-01-12 22:08 UTC, KOCMOHABT1 commented on Drozdov/README.md
> +
Я понял, что требовалось, переделал

2020-01-13 05:20 UTC, hombit requested changes

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +        translate = soup.find(string=re.compile("Перевод:")).parent.find_previous().text
Зачем здесь регулярное выражение?

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +def api_key_picture(api_key):
Эта функция почти полностью копирует предыдущую, следует вынести общую функциональность

2020-01-13 05:20 UTC, hombit commented on Drozdov/README.md
> +выводит саму картинку с русским и английским описанием. Также работает без указания даты или ключа с датой.
Странная идея просить пользователя послать вам ключ по незащищенному соединению

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +def api_picture():
Опять копирование кода

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +        return 'На дату: ' + date_astro + ' астрономической картинки дня нет.'
Следует вернуть ответ с кодом 404

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +def api_key(api_key):
Копирует предыдущую функцию

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +def api():
Копирует предыдущую функцию

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +    date_astro = date[8:10] + '.' + date[5:7] + '.' + date[:4]
Для таких вещей следует использовать какую-нибудь библиотечную функцию, например из модуля стандартной библиотеки datetime. Это позволит правильно обработать ошибочный формат даты, указанный в URL

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +    return res
Более питоновски сделать просто `return r, date, date_astro`

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +                                                                                                    'нет')
Используйте форматирование вместо конкатенации

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +    url = url_add.split('\"')[1]
Используйте модуль стандартной библиотеки `urllib.parse` для манипуляций с URL

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +        exp_rus = 'Русский перевод отсутствует.'
Что здесь происходит? Что за магическая константа 10, `len("Пояснение:")`? Тогда следовало так и написать

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +        date = r["date"]
У меня программа падает в этом месте за неимением "date" в r, пробую `/API_KEY/DATE`

2020-01-13 05:20 UTC, hombit commented on Drozdov/apodrus.py
> +    date_astro = res[2]
Если исправить return в gain_json, тот тут можно просто написать `r, date, date_astro = gain_json(api_key, date)`.

2020-01-13 05:21 UTC, hombit commented on Drozdov/apodrus.py
> +        date = r["date"]
Возможно у меня не тот ключ, но падать все равно не должно

2020-01-13 08:58 UTC, KOCMOHABT1 commented on Drozdov/apodrus.py
> +        translate = soup.find(string=re.compile("Перевод:")).parent.find_previous().text
Затем, что в случае отсутствия графы "Перевод" в астронете функция soup.find(string=re.compile("Перевод:")) возвращает не пустую строку

2020-01-13 09:15 UTC, hombit commented on Drozdov/apodrus.py
> +        translate = soup.find(string=re.compile("Перевод:")).parent.find_previous().text
Непонятно, не вижу никакой разницы с регулярным выражением и без

2020-01-13 09:18 UTC, hombit requested changes

2020-01-13 09:18 UTC, hombit commented on Drozdov/apodrus.py
> +            exp_rus = exp_rus[exp_pos + len("Пояснение:"):exp_rus.find(month, exp_pos) - 4]
Что за магическая константа "-4"?

2020-01-13 09:18 UTC, hombit commented on Drozdov/apodrus.py
> +        url = 'http://www.astronet.ru' + url
Зачем это нужно? `urllib.parse` за вас решает такие проблемы

2020-01-13 09:22 UTC, KOCMOHABT1 commented on Drozdov/apodrus.py
> +        translate = soup.find(string=re.compile("Перевод:")).parent.find_previous().text
Просто, если нет графы с переводом, метод soup.find(string=re.compile("Перевод:")).parent не работает и программа падает

2020-01-13 09:29 UTC, KOCMOHABT1 commented on Drozdov/apodrus.py
> +            exp_rus = exp_rus[exp_pos + len("Пояснение:"):exp_rus.find(month, exp_pos) - 4]
Текст перевода в астронете лежит не в отдельном теге и как зря. Поэтому способ его доставки получился сложным. Программа достаёт текст перевода, но в него попадает мусор. Это происходит для старых дат, но каждый мусор начинается с "<< Название_месяца >>". Однако на некоторых датах могут отсутствовать знаки "<<" и ">>". Поэтому для обрезки мусора программа находит строчку с месяцем и берёт всё до него, отступая 4 символа, чтобы элемент "<<" не попал в текст.

2020-01-13 09:35 UTC, hombit commented on Drozdov/apodrus.py
> +        translate = soup.find(string=re.compile("Перевод:")).parent.find_previous().text
Так и так падает
```python
In [5]: bs4.BeautifulSoup(requests.get('http://yandex.ru').text).find(string=re.compile('Пе
   ...: ревод:')).parent
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-e9bb2d9a0c32> in <module>()
----> 1 bs4.BeautifulSoup(requests.get('http://yandex.ru').text).find(string=re.compile('Перевод:')).parent

AttributeError: 'NoneType' object has no attribute 'parent'

In [6]: bs4.BeautifulSoup(requests.get('http://yandex.ru').text).find(string='Перевод:').pa
   ...: rent
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-ee8c5ce9708c> in <module>()
----> 1 bs4.BeautifulSoup(requests.get('http://yandex.ru').text).find(string='Перевод:').parent

AttributeError: 'NoneType' object has no attribute 'parent'
```

2020-01-13 09:40 UTC, KOCMOHABT1 commented on Drozdov/apodrus.py
> +        translate = soup.find(string=re.compile("Перевод:")).parent.find_previous().text
В смысле так и так? При каком вводе она падает? У меня программа работает для годов (например, 1995-06-16), где отсутствует Автор перевода

2020-01-13 10:43 UTC, hombit requested changes
Пожалуйста, сохраните английское описание, добавив русское в другие поля. Исправьте падения программы, когда запрашивается несуществующий ресурс, например `/robots.txt`.

2020-01-13 10:43 UTC, hombit commented on Drozdov/apodrus.py
> +@app.route('/<api_key>/<date>')
Эта функция копирует достаточно много кода предыдущей

2020-01-13 10:43 UTC, hombit commented on Drozdov/apodrus.py
> +        r['explanation'] = exp_rus.strip()
Пожалуйста, очистите описание от избыточных пробельных символов

2020-01-13 12:34 UTC, hombit commented on Drozdov/apodrus.py
> +    url = urllib.parse.urljoin(url, f'http://www.astronet.ru{url}')
Тут всегда будет возвращен второй аргумент

2020-01-13 12:57 UTC, KOCMOHABT1 commented on Drozdov/apodrus.py
> +@app.route('/<api_key>/<date>')
Немного упростил

2020-01-13 14:46 UTC, closed without merging