Alpha-версия проекта для поиска статей в истине.
hombit/sai-tasks2019 pull request #38
Opened 2020-12-24 15:59 UTC by Proton1904

см. README и комментарии в коде

2020-12-28 11:11 UTC, hombit requested changes
Выглядит очень круто! Думаю надо ограничить число проверяемых сотрудников, чтоб работало не очень долго. В принципе, можно было бы запускать функцию с парсингом страниц сотрудников, но и так сделано достаточно в области парсинга истины.

Пожалуйста, исправьте небольшие замечания и дайте знать когда код будет готов для запуска

2020-12-28 11:11 UTC, hombit commented on Nekrasov/istina.py
> +    else:
else не нужен

2020-12-28 11:11 UTC, hombit commented on Nekrasov/istina.py
> +    except Exception:
Слишком широкий except. Я бы предпочел явно написать r.raise_for_status и перехватить исключение выше

2020-12-28 11:11 UTC, hombit commented on Nekrasov/istina.py
> +    in_current = pub_date == get_date_current_month() and pub_date != None
Идиоматический пусть определения того, что объект — это `None`:
```python
pub_date is not None
```

2020-12-28 11:11 UTC, hombit commented on Nekrasov/istina.py
> +    if articles_presoup == None: # если страничка на истине не имеет части со статьями, то искать нечего
```python
if article_presoup is None
```
или
```python
if not article_presoup
```

2020-12-28 11:11 UTC, hombit commented on Nekrasov/istina.py
> +        str_link = 'https://istina.msu.ru' + cut_link
urrlib.parse.urljoin

2020-12-28 16:02 UTC, Proton1904 commented
Хорошо, я учел данные замечания. Exception заменил на проверку статус кода, а не raise_for_status. Вроде бы это аналогично в данном случае.
См. обновленный скрипт.

Также я добавил проверку на год последней публикации через истину, без поиска по doi. Это позволило немного ускорить работу скрипта - меньше запросов к doi.

А еще добавил парсинг аргументов. Они все опциональные, но теперь можно настраивать не только стартовую страницу поиска, но и конечную. И выбирать булевыми аргументами, искать статьи только в предыдущем месяце, только в текущем или в обоих. Сейчас еще обновлю requirements, т.к. появились новые библиотеки.

2020-12-28 16:09 UTC, Proton1904 commented
P.S. Все равно есть ощущение, что определенная доля статей либо заливается на истину без указания doi, либо doi указывается неверно (на нескольких страницах сталкивался с тем, что адрес при переходе по doi просто не открывается), либо статья заливается с большим опозданием (несколько месяцев) по времени относительно времени публикации. Скрипт пишет предупреждения о таких случаях, и их довольно много. Все-таки надеюсь, что теряется не очень существенная доля статей.

2020-12-28 16:11 UTC, hombit commented on Nekrasov/README.md
> +Этот скрипт позволяет искать новые статьи сотрудников организации на ИСТИНЕ https://istina.msu.ru/
Добавьте, пожалуйста, пример использования из командной строки

2020-12-28 16:12 UTC, hombit commented
Я думаю это нестрашно, плохие дои — не ваша проблема, а Истины

2020-12-28 16:37 UTC, Proton1904 commented
Добавил несколько примеров в README.

2020-12-29 10:29 UTC, Proton1904 commented
Добрый день. 
Сейчас я еще немного поработал над парсингом аргументов и поиском по спискам сотрудников. В последней версии булевы аргументы должны работать корректно - в ридми я тоже отразил эти изменения. А еще важное изменение - добавил еще один аргумент -r, по которому можно задать адрес организации в командную строку - это не обязательно должен быть гаиш. Можно выбрать в том числе любое подразделение гаиш, тогда поиск будет просматривать меньше страниц, и, соответственно, полный цикл работы скрипта займет меньшее время. Больше я пока ничего менять не планирую.

2020-12-29 13:54 UTC, hombit commented on Nekrasov/requirements.txt
> +datetime
Модуль стандартной библиотеки

2020-12-29 13:54 UTC, hombit commented on Nekrasov/requirements.txt
> +argparse
Как и эти три

2020-12-29 14:46 UTC, Proton1904 commented on Nekrasov/requirements.txt
> +argparse
Обновил

2020-12-30 09:38 UTC, merged

2020-12-30 09:38 UTC, hombit commented
Отлично!